State:6
Info:正式版 1.20.1, Forge 47.4.0
Logo:pack://application:,,,/images/Blocks/RedstoneLampOn.png
ReleaseTime:2023-06-12 06:25
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:47.4.0
VersionNeoForge:
VersionApiCode:47040000
VersionOriginal:1.20.1
VersionOriginalMain:20
VersionOriginalSub:1
VersionArgumentIndieV2:True
LogoCustom:True
VersionRamType:1
VersionRamCustom:29
VersionArgumentJavaSelect:{"Path":"C:\\Program Files\\Java\\openjdk-21.0.2\\bin\\","VersionString":"1.21.0.2","IsJre":false,"Is64Bit":true,"IsUserImport":false}
VersionAdvanceJvm:-XX:+UseZGC -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+PerfDisableSharedMem
VersionVanillaName:1.20.1
VersionVanilla:20.0.1
