State:6
VersionVanillaName:1.20.1
VersionArgumentIndieV2:True
VersionVanilla:20.0.1
Info:正式版 1.20.1, Forge 47.4.0
VersionLiteLoader:False
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
ReleaseTime:2023-06-12 06:25
VersionForge:47.4.0
