// priority: 150
// 攻击， 生命， 护甲
/**
 * 生物对应的模板
 */
const mobTypes = new Map([
    ['productivebees:configurable_bee', type0],
    ['productivebees:sweat_bee', type0],
    ['productivebees:digger_bee', type0],
    ['productivebees:mason_bee', type0],
    ['productivebees:green_carpenter_bee', type0],
    ['productivebees:yellow_black_carpenter_bee', type0],
    ["minecraft:bee", type0],
    ["productivebees:bumble_bee", type0],
    ["productivebees:reed_bee", type0],

    ["terra_entity:blue_jay", type0],
    ["minecraft:cat", type0],
    ["terra_entity:bird", type0],
    ['tofucraft:shudofuspider', typeB],
    ['tofucraft:fukumame_thower', typeA],
    ['tofucraft:zundamite', typeB],
    ['tofucraft:tofunian', typeA],
    ['tofucraft:traveler_tofunian', typeA],
    ['tofucraft:tofuslime', typeSlime],
    ['tofucraft:tofucreeper', typeB],
    ['tofucraft:tofuspider', typeB],
    ['minecraft:polar_bear', typeC],
    ['minecraft:rabbit', type0],
    ['quark:crab', type0],
    ['biomemakeover:helmit_crab', type0],
    ['terra_entity:bunny', type0],
    ['terra_entity:cardinal', type0],
    ['minecraft:wolf', type0],
    ['minecraft:horse', typeA],
    ['terra_entity:duck', typeA],
    ['terra_entity:jewel_bunny', typeA],
    ['tofucraft:tofupig', type0],
    ['tofucraft:tofufish', type0],
    ['tofucraft:tofucow', type0],
    ['minecraft:trader_llama', typeA],
    ['minecraft:wandering_trader', typeA],
    ['twilightforest:squirrel', type0],
    ['twilightforest:tiny_bird', type0],
    ['twilightforest:bighorn_sheep', type0],
    ['twilightforest:deer', type0],
    ['twilightforest:dwarf_rabbit', type0],
    ['twilightforest:boar', type0],
    ['ad_astra:lunarian', type0],

    ['tofucraft:tofu_gandlem', bossType1],

    ["minecraft:zombie", typeA],
    ["minecraft:drowned", typeA],
    ["minecraft:zombie_villager", typeA],
    ["minecraft:skeleton", typeA],
    ["minecraft:spider", typeB],
    ["minecraft:cave_spider", typeB],
    ["minecraft:creeper", typeB],
    ["minecraft:enderman", typeC],
    ["minecraft:iron_golem", typeC],
    ["minecraft:warden", typeCEX2],
    ["artifacts:mimic", typeAEX1],
    ["minecraft:illusioner", typeA],
    ["minecraft:witch", typeA],
    ["minecraft:slime", typeSlime],
    ["quark:forgotten", typeB],
    ["minecraft:husk", typeA],

    ["species:wicked", typeC],
    ["species:cliff_hanger", typeB],
    ["species:limpet", typeA],
    ["species:quake", typeD],
    ["minecraft:villager", typeA],
    ["minecraft:bat", type0],
    ["minecraft:tropical_fish", type0],
    ["minecraft:glow_squid", type0],
    ["minecraft:pig", type0],
    ["minecraft:sheep", type0],
    ["minecraft:cow", type0],
    ["quark:shiba", type0],
    ["minecraft:goat", type0],
    ["minecraft:armor_stand", type0],
    ["biomemakeover:mushroom_trader", type0],
    ["minecraft:axolotl", type0],
    ["minecraft:chicken", type0],
    ["minecraft:salmon", type0],
    ["minecraft:squid", type0],
    ["minecraft:camel", typeC],
    ["quark:stoneling", type0],
    ["quark:toretoise", typeD],
    ["species:ghoul", typeC],
    ["species:deepfish", type0],
    ["minecraft:parrot", type0],
    ["terra_entity:squirrel", type0],
    ["species:stackatick", typeA],
    ["minecraft:pillager", typeA],
    ["minecraft:vindicator", typeA],
    ["darkerdepths:body_snatcher", typeB],

    ["yungscavebiomes:ice_cube", typeSlime],
    ["terra_entity:spiked_slime", typeSlime],

    ["twilightforest:towerwood_borer", typeB],
    ["twilightforest:carminite_broodling", typeB],
    ["twilightforest:fire_beetle", typeA],
    ["twilightforest:slime_beetle", typeC],
    ["twilightforest:pinch_beetle", typeA],
    ["twilightforest:blockchain_goblin", typeA],
    ["twilightforest:lower_goblin_knight", typeD],
    ["twilightforest:upper_goblin_knight", typeB],
    ["twilightforest:skeleton_druid", typeB],
    ["twilightforest:redcap_sapper", typeA],
    ["twilightforest:redcap", typeA],
    ["twilightforest:pinch_beetle", typeB],
    ["twilightforest:kobold", typeA],
    ["twilightforest:king_spider", bossType1],
    ["twilightforest:hostile_wolf", typeB],
    ["twilightforest:helmet_crab", typeB],
    ["twilightforest:hedge_spider", typeB],
    ["twilightforest:death_tome", typeA],
    ["twilightforest:wraith", typeA],
    ["twilightforest:swarm_spider", typeB],
    ["twilightforest:mist_wolf", typeB],
    ["twilightforest:raven", type0],

    ["twilightforest:minotaur", typeAEX2],
    ["twilightforest:maze_slime", typeSlime],
    ["twilightforest:carminite_golem", typeCEX2],
    ["twilightforest:carminite_ghastling", typeB],
    ["twilightforest:carminite_ghastguard", typeB],
    ["twilightforest:stable_ice_core", typeAEX2],
    ["twilightforest:snow_guardian", typeAEX2],
    ["twilightforest:ice_crystal", typeB],
    ["twilightforest:giant_miner", typeCEX2],
    ["twilightforest:armored_giant", typeCEX2],
    ["twilightforest:yeti", typeAEX2],
    ["twilightforest:winter_wolf", typeB],
    ["twilightforest:unstable_ice_core", typeB],
    ["twilightforest:troll", typeAEX2],
    ["twilightforest:adherent", typeAEX2],
    ["twilightforest:harbinger_cube", typeCEX2],

    ["twilightforest:naga", bossType1],
    ["twilightforest:lich", bossType2],
    ["twilightforest:knight_phantom", bossType1W],
    ["twilightforest:ur_ghast", bossType2],
    ["twilightforest:minoshroom", bossType1EX1],
    ["twilightforest:hydra", bossTypeHydra],
    ["twilightforest:alpha_yeti", bossTypeAlphaYeti],
    ["twilightforest:snow_queen", bossType2EX2],

    ["ad_astra:star_crawler", typeA],
    ["ad_astra:corrupted_lunarian", typeC],
    ["minecraft:stray", typeC],
    ["minecraft:skeleton_horse", typeA],

    ["aether:aechor_plant", typeB],
    ["aether:blue_swet", typeSlime],
    ["aether:cockatrice", typeB],
    ["aether:fire_minion", typeD],
    ["aether:golden_swet", typeSlime],
    ["ancient_aether:festive_swet", typeSlime],
    ["aether:mimic", typeA],
    ["aether:sentry", typeD],
    ["aether:valkyrie", typeC],
    ["aether:zephyr", typeC],
    ["deep_aether:venomite", typeB],
    ["aether_redux:vanilla_swet", typeSlime],
    ["aether:sheepuff", type0],
    ["aether:phyg", type0],
    ["aether:moa", type0],
    ["deep_aether:aerglow_fish", type0],
    ["twilightforest:penguin", type0],
    ["deep_aether:quail", type0],
    ["aether:aerbunny", type0],
    ["aether:flying_cow", type0],

    ["aether:aerwhale", typeC],
    ["aether:whirlwind", type0],
    ["aether:evil_whirlwind", type0],
    ["species:wraptor", type0],
    ["terra_entity:goblin_tinkerer", type0],

    ["aether:valkyrie_queen", bossType1],
    ["aether:slider", bossType2],
    ["aether:sun_spirit", bossType2],
    ["aether:valkyrie_queen", bossType1],
    ["lost_aether_content:aerwhale_king", bossType2],
    ["deep_aether:eots_segment", bossType1],
    ["deep_aether:eots_controller", bossType2],

    ["terra_entity:blue_slime", typeSlime],
    ["terra_entity:purple_slime", typeSlime],
    ["terra_entity:green_slime", typeSlime],
    ["terra_entity:red_slime", typeSlime],
    ["terra_entity:yellow_slime", typeSlime],
    ["terra_entity:honey_slime", typeSlime],
    ["terra_entity:black_slime", typeSlime],
    ["terra_entity:pink_slime", typeSlime],
    ["terra_entity:dungeon_slime", typeSlime],
    ["terra_entity:desert_slime", typeSlime],
    ["terra_entity:green_dumpling_slime", typeSlime],
    ["terra_entity:swamp_slime", typeSlime],
    ["terra_entity:jungle_slime", typeSlime],
    ["terra_entity:golden_slime", typeSlime],
    ["terra_entity:jungle_bat", typeB],
    ["terra_entity:snatcher", typeA],
    ["terra_entity:man_eater", typeB],
    ["terra_entity:hornet", typeB],
    ["terra_entity:ice_slime", typeSlime],
    ["terra_entity:ice_bat", typeB],
    ["terra_entity:lava_slime", typeSlime],
    ["terra_entity:hell_bat", typeB],
    ["terra_entity:crimslime", typeSlime],
    ["terra_entity:corrupt_slime", typeSlime],
    ["terra_entity:tropic_slime", typeSlime],
    ["terra_entity:evil_slime", typeSlime],
    ["terra_entity:demon_eye", typeSlime],
    ["terra_entity:blood_crawler", typeB],
    ["terra_entity:bloody_spore", typeB],
    ["terra_entity:spore_skeleton", typeA],
    ["terra_entity:spore_zombie", typeA],
    ["terra_entity:hat_spore_zombie", typeA],
    ["terra_entity:decayeder", typeA],
    
    ["terra_entity:giant_shelly", typeC],
    ["terra_entity:giant_worm", typeD],
    ["terra_entity:dark_caster", typeB],
    ["terra_entity:undead_viking", typeA],
    ["terra_entity:goblin_sorcerer", typeA],
    ["terra_entity:goblin_archer", typeB],
    ["terra_entity:goblin_peon", typeD],
    ["terra_entity:goblin_warrior", typeC],
    ["terra_entity:goblin_thief", typeB],
    ["terra_entity:goblin_scout", typeB],
    ["terra_entity:anger_goblin", typeC],
    ["terra_entity:nymph", typeC],
    ["terra_entity:cave_bat", typeB],
    ["terra_entity:spore_bat", typeB],
    ["terra_entity:tomb_crawler", typeD],
    ["terra_entity:antlion_swarmer", typeA],
    ["terra_entity:giant_antlion", typeC],
    ["terra_entity:harpy", typeB],
    ["terra_entity:demon", typeA],
    ["terra_entity:voodoo_demon", typeA],
    ["terra_entity:drippler", typeB],
    ["terra_entity:blood_zombie", typeA],
    ["terra_entity:wandering_eye_fish", typeA],
    ["terra_entity:ghost", typeA],
    ["terra_entity:crimson_kemera", typeB],
    ["terra_entity:eater_of_souls", typeA],
    ["terra_entity:face_monster", typeA],
    ["terra_entity:fire_imp", typeB],
    ["terra_entity:snow_flinx", typeB],
    ["terra_entity:anger_bones", typeA],
    ["terra_entity:short_bones", typeB],
    ["terra_entity:big_bones", typeD],
    ["terra_entity:big_anger_bones", typeD],
    ["terra_entity:big_muscle_anger_bones", typeC],
    ["terra_entity:big_helmet_anger_bones", typeC],
    ["terra_entity:cursed_skull", typeB],

    ["terra_entity:king_slime", bossType1],
    ["terra_entity:eye_of_cthulhu", bossType1],
    ["terra_entity:eater_of_worlds", bossType2],
    ["terra_entity:brain_of_cthulhu", bossType1],
    ["terra_entity:queen_bee", bossType1],
    ["terra_entity:skeletron", bossType1],
    ["terra_entity:dungeon_guardian", bossType2EX2],
    ["terra_entity:wall_of_flesh", bossType2],
    ["terra_entity:hill_of_flesh", bossType2],
    ["terra_entity:deerclops", bossType2],

    ["minecraft:wither", bossType2],

    ["minecraft:piglin", typeA],
    ["minecraft:piglin_brute", typeAEX1],
    ["minecraft:zombified_piglin", typeA],
    ["minecraft:wither_skeleton", typeA],
    ["minecraft:blaze", typeA],
    ["minecraft:ghast", typeA],
    ["minecraft:hoglin", typeC],
    ["minecraft:zoglin", typeC],
    ["minecraft:magma_cube", typeSlime],
    ["minecraft:strider", type0],
    ["quark:foxhound", typeB],
    ["thermal:basalz", typeA],
    ["thermal:blizz", typeA],
    ["terra_entity:the_hungry", typeB],
    ["terra_entity:hill_hungry", typeB],
    ["terra_entity:leech", typeC],
    ["quark:wraith", typeA],
    ["twilightforest:mosquito_swarm", typeB],

    ["cataclysm:netherite_monstrosity", bossType2],

    ["ad_astra:martian_raptor", typeC],

    ["minecraft:phantom", typeB],
    ["minecraft:evoker", typeA],
    ["minecraft:vex", typeSlime],

    ["minecraft:ender_dragon", bossType1],
    ["minecraft:elder_guardian", bossType1],

    ["ad_astra:pygro", typeA],
    ["ad_astra:pygro_brute", typeAEX1],
    ["ad_astra:zombified_pygro", typeA],
    ["ad_astra:mogler", typeA],
    ["ad_astra:zombified_mogler", typeC],

    ["nuclearcraft:feral_ghoul", typeA],
    ["undergarden:rotbeast", typeC],
    ["undergarden:rotling", typeB],
    ["undergarden:rotwalker", typeA],
    ["undergarden:forgotten", typeD],
    ["undergarden:minion", typeD],
    ["undergarden:sploogie", typeSlime],
    ["undergarden:nargoyle", typeB],
    ["undergarden:muncher", typeA],
    
    ["undergarden:brute", type0],
    ["undergarden:scintling", typeSlime],
    ["undergarden:gwib", type0],
    ["undergarden:gwibling", type0],
    ["undergarden:stoneborn", typeA],
    ["undergarden:mog", type0],
    ["undergarden:dweller", type0],

    ["undergarden:forgotten_guardian", bossType1],
    ["nuclearcraft:feral_ghoul_boss", typeAE],
    ["final_samurai:samurai", bossType1EX1],

    ["midnight:rifter", typeA],
    ["midnight:nightshade", typeC],
    ["midnight:slink", typeD],
    ["midnight:nightstag", typeD],
    ["midnight:nova", typeB],
    ["midnight:stinger", typeB],
    ["midnight:crystal_bug", typeB],

    ["cataclysm:urchinkin", type0],
    ["cataclysm:drowned_host", typeA],
    ["cataclysm:symbiocto", typeB],
    ["cataclysm:hippocamtus", typeD],
    ["cataclysm:cindaria", typeC],
    ["cataclysm:koboleton", typeC],
    ["cataclysm:wadjet", typeA],
    ["cataclysm:endermaptera", typeB],

    ["cataclysm:the_watcher", type0],

    ["cataclysm:the_prowler", typeAE],
    ["cataclysm:clawdian", typeAE],
    ["cataclysm:kobolediator", typeAE],
    ["cataclysm:ignited_revenant", typeAE],
    ["cataclysm:ender_golem", typeAE],

    ["cataclysm:scylla", bossType1],
    ["cataclysm:the_harbinger", bossType1],
    ["cataclysm:ancient_remnant", bossType1],
    ["cataclysm:ignis", bossType1],

    ["minecraft:shulker", typeD],

    ["cataclysm:lionfish", type0],
    ["cataclysm:deepling_angler", typeB],
    ["cataclysm:deepling", typeA],
    ["cataclysm:deepling_brute", typeD],
    ["cataclysm:deepling_priest", typeA],
    ["cataclysm:deepling_warlock", typeA],

    ["cataclysm:coralssus", typeAE],

    ["cataclysm:the_leviathan", bossType2],
    ["cataclysm:the_leviathan", bossType2],

    ["cataclysm:the_baby_leviathan", typeA],

    ["terra_entity:arapaima", typeC],
    ["terra_entity:shark", typeA],
    ["terra_entity:granite_elemental", typeD],
    ["terra_entity:flying_fish", typeSlime],
    ["terra_entity:green_jellyfish", typeSlime],
    ["terra_entity:blue_jellyfish", typeSlime],
    ["terra_entity:pink_jellyfish", typeA],
    ["terra_entity:pixie", typeB],
    ["terra_entity:piranha", typeB],

]);

/**
 * 黑名单
 */
const entityBlackList = new Set([
    "powerful_dummy:test_dummy",
    "terra_entity:summon_diamond_sword",
    "terra_entity:summon_golden_sword",
    "terra_entity:summon_imp",
    "terra_entity:summon_iron_sword",
    "terra_entity:summon_netherite_sword",
    "terra_entity:summon_snow_flinx",
    "terra_entity:summon_stone_sword",
    "terra_entity:summon_wooden_sword"
]);

ServerEvents.tags("entity_type", event => {
    mobTypes.forEach((type, e) => {
        // console.log(e);
        if (type.isBoss) {
            event.add("enderio:soul_vial_blacklist", e);
            // console.log(e);
        }

    });


});
