const toRemoveID = new Set([
    "easy_villagers:farmer",
    "easy_villagers:iron_farm",
    "minecraft:enchanting_table",
    "apotheosis:library",
    "apotheosis:enchanting/ender_library",
    "dustandash:crafting/sharpen_flint",
    "slashblade:material/sphere_smelting",
    "enderio:smelting/slashblade/material/sphere_smelting",
    "slashblade:material/crystal_blasting",
    "slashblade:material/trapezohedron_blasting",
    "thermal:fire_charge/signalum_glass_2",
    "thermal:fire_charge/obsidian_glass_2",
    "thermal:fire_charge/lumium_ingot_4",
    "thermal:fire_charge/enderium_ingot_2",
    "thermal:fire_charge/electrum_ingot_2",
    "thermal:fire_charge/constantan_ingot_2",
    "thermal:fire_charge/bronze_ingot_4",
    "thermal:fire_charge/enderium_glass_2",
    "thermal:fire_charge/signalum_ingot_4",
    "thermal:fire_charge/lumium_glass_2",
    "thermal:fire_charge/invar_ingot_3",
    "thermal:machine_frame",
    "thermal:rf_coil",
    "ad_astra:desh_engine",
    "nuclearcraft:plate_basic2",
    "nuclearcraft:plate_basic",
    "ancient_aether:enchanting_table_from_gravitite",
    "confluence:workshop",

    "slashblade_addon:wanderer",
    "cialloblade:ciallo",
    "slashblade:muramasa",
    "last_smith:kataware_exorcism_sakura",
    "last_smith:kataware_exorcism_yuki",
    "last_smith:kataware_exorcism_ginkgo",
    "slashblade_addon:frosty_cherry",
    "slashblade:ruby",
    "pseudoedge_break_dawn:purplesblade",
    "last_smith:exorcism_yuki",
    "last_smith:exorcism_sakura",
    "blades_derby:uma_black",
    "pseudoedge_break_dawn:kingblade",
    "slashblade_addon:nihil",
    "pseudoedge_break_dawn:kumasakura",

    "foxextra:foxex_white",
    "pseudoedge_break_dawn:vitex",
    "slashblade:material/ingot",
    "last_smith:blade_step_1",
    "slashblade:fox_white",
    "slashblade:fox_black",
    "last_smith:sakura_steel",
    "slashblade:yuzukitukumo",
    "blades_derby:uma_hishi",
    "sjap_adder:agito_ex",
    "slashblade:sabigatana",
    "slashblade:doutanuki",
    "slashblade:orotiagito",
    "undergarden:catalyst",
    "slashblade_addon:nihilex",
    "pseudoedge_break_dawn:magicblade",
    "pseudoedge_break_dawn:xblades",
    "enderio:void_chassis",

    "pseudoedge_break_dawn:pseudosword",
    "pseudoedge_break_dawn:blackpixie",
    "pseudoedge_break_dawn:latent",

    "slashblade_addon:yukari",
    
    "blades_derby:uma_odachi_haru",
    "blades_derby:uma_odachi_halo",
    "slashblade:egg_lan",

    "slashblade_addon:kirisaya",

    // s3
    "slashblade:ruined_sword",
    "last_smith:bloodybamboo",
    "last_smith:goldenbamboo",
    "slashblade:air_sword",
    "foxextra:foxex_black",
    "slashblade:kanze_masamune",
    "slashblade:moonveil",
    "slashblade:bizen_osafune_nagamitsu",
    "energyblade:hf_blade",
    "slashblade:dissociator",

    "slashblade:rivers_of_blood",
    "slashblade:clothesline",
    "slashblade_addon:moonlight_cherry",
    "slashblade_addon:green_mist",
    "slashblade:hand_of_malenia",
    "slashblade:ssa_kagari",
    "slashblade:ssa_hayate",
    "sjap_adder:toyoko",

    "sjap_adder:agito_true_ex",
    "slashblade:ssa_roze",
    "slashblade:ssa_raye",
    "last_smith:evil_shura",
    "sjap_adder:nihil_soul",

    "last_smith:nameless_odachi",
    "last_smith:muramasa_kagura",
    "sjap_adder:black_soul",
    "last_smith:hakurouken",

    "slashblade_addon:kamuy_none",
    "last_smith:oboro_muramasa",
    "last_smith:roukanken",
    "pseudoedge_break_dawn:dragonblade",

    // 临时
    "apotheosis:hellshelf",
    "apotheosis:enchanting/infused_hellshelf",
    "apotheosis:blazing_hellshelf",
    "apotheosis:glowing_hellshelf",
    "apotheosis:seashelf",
    "apotheosis:enchanting/infused_seashelf",
    "apotheosis:crystal_seashelf",
    "apotheosis:heart_seashelf",
    "apotheosis:dormant_deepshelf",
    "apotheosis:enchanting/deepshelf",
    "apotheosis:echoing_deepshelf",
    "apotheosis:soul_touched_deepshelf",
    "apotheosis:echoing_sculkshelf",
    "apotheosis:soul_touched_sculkshelf",
    "apotheosis:endshelf",
    "apotheosis:pearl_endshelf",
    "apotheosis:draconic_endshelf",
    "apotheosis:beeshelf",
    "apotheosis:melonshelf",
    "apotheosis:stoneshelf",
    "apotheosis:rectifier",
    "apotheosis:rectifier_t2",
    "apotheosis:rectifier_t3",
    "apotheosis:sightshelf",
    "apotheosis:sightshelf_t2",
    "apotheosis:filtering_shelf",
    "apotheosis:treasure_shelf"
]);

ServerEvents.recipes(event => {
    for (const id of toRemoveID) {
        event.remove({ id: id });
    }

    event.remove({ output: '#forge:gears', type: 'minecraft:crafting_shaped', mod: "thermal" });

})
