"""Build the runtime identity catalogue from the reviewed design table (UTF-8)."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
source = (ROOT / 'dev_docs/宝石设计表.md').read_text(encoding='utf-8-sig')
species = []
rules = []
greek = {'α': 'alpha', 'β': 'beta', 'γ': 'gamma', 'δ': 'delta'}
stats = {'大': 'size', '纯': 'purity', '抛': 'polish'}
roles = {'原生': 'producer', '放大': 'amplifier', '转换': 'converter'}
for line in source.splitlines():
    cells = [c.strip() for c in line.strip().strip('|').split('|')]
    if not line.startswith('|'):
        continue
    if len(cells) == 4 and re.fullmatch(r'`[a-z0-9_.-]+:[a-z0-9_/.-]+`', cells[1]):
        species.append({'name': cells[0], 'item': cells[1].strip('`'), 'number': len(species) + 1})
    if len(cells) == 7 and cells[1] in greek:
        kind = next(s for s in species if s['name'] == cells[0])
        main, badge_main = cells[5].split('／')
        rules.append({'item': kind['item'], 'kind': kind['number'], 'name': cells[0],
                      'primary': greek[cells[1]], 'letter': cells[1], 'role': roles[cells[2]],
                      'mechanic': cells[3], 'badgeText': cells[4],
                      'main': stats[main], 'badgeMain': stats[badge_main]})
assert len(species) == 34 and len(rules) == 84
assert len({r['item'] + '#' + r['primary'] for r in rules}) == 84

out = ROOT / 'kubejs/startup_scripts/astral_gems/00_catalog.js'
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('// priority: 1900\n// Generated by kubejs/tools/astral_gems/build_catalog.py.\n'
               'global.sdbfAstral = {\n'
               '  fillerId: "kubejs:astral_gem_filler",\n'
               '  badgeId: "kubejs:astral_gem_badge",\n'
               '  gemKey: "sdbf.astral_gem", badgeKey: "sdbf.astral_badge",\n'
               '  balance: null, apiReady: false,\n'
               '  species: ' + json.dumps(species, ensure_ascii=False, indent=2) + ',\n'
               '  rules: ' + json.dumps(rules, ensure_ascii=False, indent=2) + '\n};\n', encoding='utf-8')
print(f'Generated {len(species)} species and {len(rules)} rules: {out.relative_to(ROOT)}')
