// priority: 1900
// Generated by kubejs/tools/astral_gems/build_catalog.py.
global.sdbfAstral = {
  fillerId: "kubejs:astral_gem_filler",
  badgeId: "kubejs:astral_gem_badge",
  gemKey: "sdbf.astral_gem", badgeKey: "sdbf.astral_badge",
  balance: null, apiReady: false,
  species: [
    {
      "name": "粗制绿宝石",
      "item": "tetra:pristine_emerald",
      "number": 1
    },
    {
      "name": "粗制青金石",
      "item": "tetra:pristine_lapis",
      "number": 2
    },
    {
      "name": "粗制钻石",
      "item": "tetra:pristine_diamond",
      "number": 3
    },
    {
      "name": "石英",
      "item": "minecraft:quartz",
      "number": 4
    },
    {
      "name": "粗制紫水晶",
      "item": "tetra:pristine_amethyst",
      "number": 5
    },
    {
      "name": "海晶砂粒",
      "item": "minecraft:prismarine_crystals",
      "number": 6
    },
    {
      "name": "充能赛特斯石英水晶",
      "item": "ae2:charged_certus_quartz_crystal",
      "number": 7
    },
    {
      "name": "福鲁伊克斯水晶",
      "item": "ae2:fluix_crystal",
      "number": 8
    },
    {
      "name": "魔力钻石",
      "item": "botania:mana_diamond",
      "number": 9
    },
    {
      "name": "龙石",
      "item": "botania:dragonstone",
      "number": 10
    },
    {
      "name": "穹玉晶石",
      "item": "deep_aether:skyjade",
      "number": 11
    },
    {
      "name": "脉冲水晶",
      "item": "enderio:pulsating_crystal",
      "number": 12
    },
    {
      "name": "振动水晶",
      "item": "enderio:vibrant_crystal",
      "number": 13
    },
    {
      "name": "末影水晶",
      "item": "enderio:ender_crystal",
      "number": 14
    },
    {
      "name": "诱引水晶",
      "item": "enderio:enticing_crystal",
      "number": 15
    },
    {
      "name": "天气水晶",
      "item": "enderio:weather_crystal",
      "number": 16
    },
    {
      "name": "预知水晶",
      "item": "enderio:prescient_crystal",
      "number": 17
    },
    {
      "name": "砷化硼",
      "item": "nuclearcraft:boron_arsenide_gem",
      "number": 18
    },
    {
      "name": "方氟钾石",
      "item": "nuclearcraft:carobbiite_gem",
      "number": 19
    },
    {
      "name": "氟盐",
      "item": "nuclearcraft:villiaumite_gem",
      "number": 20
    },
    {
      "name": "氟石",
      "item": "nuclearcraft:fluorite_gem",
      "number": 21
    },
    {
      "name": "菱锰",
      "item": "nuclearcraft:rhodochrosite_gem",
      "number": 22
    },
    {
      "name": "六方氮化硼",
      "item": "nuclearcraft:boron_nitride_gem",
      "number": 23
    },
    {
      "name": "紫晶石",
      "item": "aether:zanite_gemstone",
      "number": 24
    },
    {
      "name": "砷铅铁矿石",
      "item": "twilightforest:carminite",
      "number": 25
    },
    {
      "name": "磷灰石",
      "item": "thermal:apatite",
      "number": 26
    },
    {
      "name": "朱砂",
      "item": "thermal:cinnabar",
      "number": 27
    },
    {
      "name": "硝石",
      "item": "thermal:niter",
      "number": 28
    },
    {
      "name": "红宝石",
      "item": "thermal:ruby",
      "number": 29
    },
    {
      "name": "蓝宝石",
      "item": "thermal:sapphire",
      "number": 30
    },
    {
      "name": "充能红石",
      "item": "appflux:charged_redstone",
      "number": 31
    },
    {
      "name": "豆腐宝石",
      "item": "tofucraft:tofugem",
      "number": 32
    },
    {
      "name": "毛豆宝石",
      "item": "tofucraft:zundaruby",
      "number": 33
    },
    {
      "name": "泪宝石",
      "item": "cataclysm:lacrima",
      "number": 34
    }
  ],
  rules: [
    {
      "item": "tetra:pristine_emerald",
      "kind": 1,
      "name": "粗制绿宝石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产体质；相邻生效宝石的不同种类越多，乘增次数越多，同种只计一次。",
      "badgeText": "体质 → 最大生命值",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "tetra:pristine_emerald",
      "kind": 1,
      "name": "粗制绿宝石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取最多三个不同邻格的原生来源，每颗取一种分数，汇总转为体质；输入分数类型越多，转换倍率越高。",
      "badgeText": "体质 → 受到治疗倍率",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "tetra:pristine_lapis",
      "kind": 2,
      "name": "粗制青金石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产智力；当前经验等级提高产分，等级带来的额外收益逐渐放缓。",
      "badgeText": "智力 → 经验获取",
      "main": "size",
      "badgeMain": "polish"
    },
    {
      "item": "tetra:pristine_lapis",
      "kind": 2,
      "name": "粗制青金石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取一组相对邻格的感知和魔力，汇总转为智力；自动选择符合条件的横向或纵向组合。",
      "badgeText": "智力 → 魔法穿透",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "tetra:pristine_diamond",
      "kind": 3,
      "name": "粗制钻石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产敏捷；修正后三维每有一项超过对应天然上限，追加一次乘增，最多按三个维度计。",
      "badgeText": "敏捷 → 盔甲穿透",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "tetra:pristine_diamond",
      "kind": 3,
      "name": "粗制钻石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取体质转为力量；自身归一化超限幅度最大的一项提供额外转换奖励，未超限时仍可正常转换。",
      "badgeText": "力量 → 盔甲撕裂",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "minecraft:quartz",
      "kind": 4,
      "name": "石英",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产感知；每个四向相邻的开放且物理为空的格子追加一次乘增，关闭格及网格外不计。",
      "badgeText": "感知 → 经验获取",
      "main": "size",
      "badgeMain": "polish"
    },
    {
      "item": "minecraft:quartz",
      "kind": 4,
      "name": "石英",
      "primary": "beta",
      "letter": "β",
      "role": "producer",
      "mechanic": "自产魔力；每颗相邻生效石英填充物追加一次乘增，石英的任意主修饰均可计入。",
      "badgeText": "魔力 → 魔法穿透",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "tetra:pristine_amethyst",
      "kind": 5,
      "name": "粗制紫水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "按主世界昼夜切换产分类型：白天敏捷、夜晚魔力；夜晚的效率较高。",
      "badgeText": "敏捷＋魔力 → 暴击率",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "tetra:pristine_amethyst",
      "kind": 5,
      "name": "粗制紫水晶",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "白天读取魔力转为敏捷，夜晚读取敏捷转为魔力；夜晚效率较高。",
      "badgeText": "敏捷＋魔力 → 暴击伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "minecraft:prismarine_crystals",
      "kind": 6,
      "name": "海晶砂粒",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产感知；自身修正后三维的归一化数值越接近，额外奖励越高，偏科仍保留正常基础产分。",
      "badgeText": "感知 → 受到治疗倍率",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "minecraft:prismarine_crystals",
      "kind": 6,
      "name": "海晶砂粒",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取两个不同邻格的原生魔力，以较小者为放大主体。",
      "badgeText": "魔力 → 寒冰伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "minecraft:prismarine_crystals",
      "kind": 6,
      "name": "海晶砂粒",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取正体质、正魔力，将两者差值转为其中较低的分数类型。",
      "badgeText": "体质 → 受到治疗倍率；魔力 → 寒冰伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "ae2:charged_certus_quartz_crystal",
      "kind": 7,
      "name": "充能赛特斯石英水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产感知；实际暴击率越接近固定目标，奖励越高，达到目标后保持满条件收益。",
      "badgeText": "感知 → 经验获取",
      "main": "size",
      "badgeMain": "polish"
    },
    {
      "item": "ae2:charged_certus_quartz_crystal",
      "kind": 7,
      "name": "充能赛特斯石英水晶",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取感知与另一邻格的敏捷，输出感知×(1＋敏捷/K)；两个来源必须不同。",
      "badgeText": "感知 → 暴击率",
      "main": "purity",
      "badgeMain": "size"
    },
    {
      "item": "ae2:charged_certus_quartz_crystal",
      "kind": 7,
      "name": "充能赛特斯石英水晶",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取感知；实际暴击率低于目标时转为敏捷，达到目标时转为魔力，与本种α使用同一目标。",
      "badgeText": "敏捷＋魔力 → 暴击伤害",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "ae2:fluix_crystal",
      "kind": 8,
      "name": "福鲁伊克斯水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "converter",
      "mechanic": "读取力量，按核心固定比例拆分为敏捷和魔力。",
      "badgeText": "敏捷＋魔力 → 拔刀剑伤害系数",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "ae2:fluix_crystal",
      "kind": 8,
      "name": "福鲁伊克斯水晶",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取三个不同邻格的力量、感知、魔力，以三者乘积/K²转为智力；允许固定名单中的加工来源。",
      "badgeText": "智力 → 癫火伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "ae2:fluix_crystal",
      "kind": 8,
      "name": "福鲁伊克斯水晶",
      "primary": "gamma",
      "letter": "γ",
      "role": "amplifier",
      "mechanic": "读取至少两个魔力来源，取最高与最低，输出最高值×(1＋差值/K)；允许固定名单中的加工来源。",
      "badgeText": "魔力 → 火焰伤害、寒冰伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "botania:mana_diamond",
      "kind": 9,
      "name": "魔力钻石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产魔力；不存在负面附加词条时获得额外乘增。",
      "badgeText": "魔力 → 魔法穿透",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "botania:mana_diamond",
      "kind": 9,
      "name": "魔力钻石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取相邻来源的加工增量Δ，选择最高者转为魔力。",
      "badgeText": "魔力 → 寒冰伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "botania:mana_diamond",
      "kind": 9,
      "name": "魔力钻石",
      "primary": "gamma",
      "letter": "γ",
      "role": "amplifier",
      "mechanic": "读取魔力，以来源加工比例继续放大：魔力×(1＋Δ/B)；额外允许读取本种β，要求来源B>0。",
      "badgeText": "魔力 → 癫火伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "botania:dragonstone",
      "kind": 10,
      "name": "龙石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产力量；实际拔刀剑伤害系数接近固定目标时奖励提高，达到目标后保持满条件收益。",
      "badgeText": "力量 → 暴击伤害",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "botania:dragonstone",
      "kind": 10,
      "name": "龙石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取体质，拆分为保留体质与生成力量；实际盔甲穿透越高，力量份额越大，总分配规则固定。",
      "badgeText": "力量 → 癫火伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "botania:dragonstone",
      "kind": 10,
      "name": "龙石",
      "primary": "gamma",
      "letter": "γ",
      "role": "amplifier",
      "mechanic": "在四向距离二格处选择最高力量来源；中间格必须开放且物理为空，目标必须生效。",
      "badgeText": "力量 → 拔刀剑伤害系数",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "deep_aether:skyjade",
      "kind": 11,
      "name": "穹玉晶石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产敏捷；玩家当前离地时获得较高乘增，落地时维持基础产分。",
      "badgeText": "敏捷 → 暴击率",
      "main": "size",
      "badgeMain": "polish"
    },
    {
      "item": "deep_aether:skyjade",
      "kind": 11,
      "name": "穹玉晶石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取感知转为体质；玩家当前落地时转换效率更高。",
      "badgeText": "体质 → 受到治疗倍率",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "enderio:pulsating_crystal",
      "kind": 12,
      "name": "脉冲水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产感知；按游戏时间每60秒平滑起伏一次，波峰较高，波谷仍保留基础产分。",
      "badgeText": "感知 → 经验获取",
      "main": "size",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:pulsating_crystal",
      "kind": 12,
      "name": "脉冲水晶",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "只读取相邻脉冲水晶 α的最高感知，放大倍率与其同周期变化，使波峰进一步放大。",
      "badgeText": "感知 → 暴击率",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:vibrant_crystal",
      "kind": 13,
      "name": "振动水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "amplifier",
      "mechanic": "读取一组相对邻格的力量，以两者乘积/K输出力量；有多组时选择收益最高者。",
      "badgeText": "力量 → 拔刀剑伤害系数",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:vibrant_crystal",
      "kind": 13,
      "name": "振动水晶",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取三个不同邻格的敏捷、感知、魔力，以(敏×感＋敏×魔＋感×魔)/K转为智力。",
      "badgeText": "智力 → 暴击伤害",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "enderio:ender_crystal",
      "kind": 14,
      "name": "末影水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "amplifier",
      "mechanic": "读取四个斜角相邻格的原生敏捷，选择最高者放大。",
      "badgeText": "敏捷 → 盔甲穿透",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:ender_crystal",
      "kind": 14,
      "name": "末影水晶",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取容器中心镜像格，将其最终总分转为魔力；允许原生型、福鲁伊克斯水晶 α及粗制紫水晶 β，镜像为自身时不触发。",
      "badgeText": "魔力 → 魔法穿透",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "enderio:enticing_crystal",
      "kind": 15,
      "name": "诱引水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产感知；每个基础总分B低于自身B的相邻原生宝石追加一次固定乘增。",
      "badgeText": "感知 → 经验获取",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "enderio:enticing_crystal",
      "kind": 15,
      "name": "诱引水晶",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取至少两个正感知，以最小值×(1＋其余感知之和/K)输出感知。",
      "badgeText": "感知 → 受到治疗倍率",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:enticing_crystal",
      "kind": 15,
      "name": "诱引水晶",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "优先选择正附加词条数量最多的来源，将最终总分转为智力；同数量时选择最终总分较高者。",
      "badgeText": "智力 → 经验获取",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "enderio:weather_crystal",
      "kind": 16,
      "name": "天气水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产感知；当前维度晴天时额外乘增，雨天或雷暴时保持基础产分。",
      "badgeText": "感知 → 经验获取",
      "main": "size",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:weather_crystal",
      "kind": 16,
      "name": "天气水晶",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取两个原生魔力来源；晴天取较大值，雨天取总和，雷暴时再由较小值提供(1＋较小值/K)倍率。",
      "badgeText": "魔力 → 寒冰伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:weather_crystal",
      "kind": 16,
      "name": "天气水晶",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取不同邻格的力量、敏捷，通常以两者之和转魔力，雷暴时额外加入乘积/K。",
      "badgeText": "魔力 → 火焰伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "enderio:prescient_crystal",
      "kind": 17,
      "name": "预知水晶",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产智力；当前经验条进度越接近升级，额外产分越高，升级后依据新的进度重算。",
      "badgeText": "智力 → 暴击伤害",
      "main": "size",
      "badgeMain": "polish"
    },
    {
      "item": "enderio:prescient_crystal",
      "kind": 17,
      "name": "预知水晶",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取三个不同邻格的力量、感知、魔力汇总转智力；三者按此顺序顺时针排列时再获得一次乘增，自动识别起点。",
      "badgeText": "智力 → 癫火伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "nuclearcraft:boron_arsenide_gem",
      "kind": 18,
      "name": "砷化硼",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产体质；实际火焰伤害、寒冰伤害共同提高产分，条件收益逐渐放缓。",
      "badgeText": "体质 → 最大生命值",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "nuclearcraft:boron_arsenide_gem",
      "kind": 18,
      "name": "砷化硼",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "沿四向读取连续排列的原生魔力宝石，选择收益最高的直线；魔力汇总转力量，长度提供额外乘增；空格、关闭格或不合格来源截断。",
      "badgeText": "力量 → 火焰伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "nuclearcraft:carobbiite_gem",
      "kind": 19,
      "name": "方氟钾石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产智力；每个包含自身且四格都放有生效宝石的2×2方阵追加一次乘增，可同时属于多个方阵。",
      "badgeText": "智力 → 魔法穿透",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "nuclearcraft:carobbiite_gem",
      "kind": 19,
      "name": "方氟钾石",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "四个斜角都有原生智力来源时，输出其总和×(1＋四者最小值/K)。",
      "badgeText": "智力 → 癫火伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "nuclearcraft:carobbiite_gem",
      "kind": 19,
      "name": "方氟钾石",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "选择包含自身的完整2×2方阵，以其余三颗宝石的B₁B₂B₃/K²转为感知；来源可为任意宝石主修饰。",
      "badgeText": "感知 → 经验获取",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "nuclearcraft:villiaumite_gem",
      "kind": 20,
      "name": "氟盐",
      "primary": "alpha",
      "letter": "α",
      "role": "converter",
      "mechanic": "读取最高力量来源，转换所得固定等分为智力、感知、魔力。",
      "badgeText": "智力＋魔力 → 魔法穿透",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "nuclearcraft:villiaumite_gem",
      "kind": 20,
      "name": "氟盐",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "只读取相邻氟盐 α或福鲁伊克斯水晶 α，选最终总分较高者汇总转感知；来源实际正分数类型越多，转换倍率越高。",
      "badgeText": "感知 → 受到治疗倍率",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "nuclearcraft:fluorite_gem",
      "kind": 21,
      "name": "氟石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产感知；相邻生效宝石每出现一种不同角色——原生、放大、转换——追加一次乘增。",
      "badgeText": "感知 → 经验获取",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "nuclearcraft:fluorite_gem",
      "kind": 21,
      "name": "氟石",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取两颗福鲁伊克斯水晶 α或氟盐 α，对双方共有的分数类型逐项输出两者该项分数乘积/K。",
      "badgeText": "智力＋魔力 → 火焰伤害、寒冰伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "nuclearcraft:fluorite_gem",
      "kind": 21,
      "name": "氟石",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取一颗福鲁伊克斯水晶 α或氟盐 α，保留其最高一项分数，将其余各项汇总转为感知。",
      "badgeText": "感知 → 魔法穿透",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "nuclearcraft:rhodochrosite_gem",
      "kind": 22,
      "name": "菱锰",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产体质；四向连通的每颗其他生效菱锰宝石追加一次乘增，本种任意主修饰均可计入。",
      "badgeText": "体质 → 最大生命值",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "nuclearcraft:rhodochrosite_gem",
      "kind": 22,
      "name": "菱锰",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "只读取相邻菱锰 α的最高体质，其所属菱锰连片越大，额外放大越强。",
      "badgeText": "体质 → 受到治疗倍率",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "nuclearcraft:rhodochrosite_gem",
      "kind": 22,
      "name": "菱锰",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "从不同邻格读取菱锰 β或粗制绿宝石 β的体质及原生感知，以体质×(1＋感知/K)转为智力。",
      "badgeText": "智力 → 癫火伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "nuclearcraft:boron_nitride_gem",
      "kind": 23,
      "name": "六方氮化硼",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产体质；每个直接接触容器网格外边界的方向追加一次乘增，角落通常计两次。",
      "badgeText": "体质 → 盔甲撕裂",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "nuclearcraft:boron_nitride_gem",
      "kind": 23,
      "name": "六方氮化硼",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取粗制绿宝石 β、龙石 β、穹玉晶石 β或菱锰 β的体质，取C＝g×体质，输出C(1＋C/K)。",
      "badgeText": "体质 → 最大生命值",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "nuclearcraft:boron_nitride_gem",
      "kind": 23,
      "name": "六方氮化硼",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取不同邻格的体质、魔力，以较小值X(1＋X/K)转为力量；体质还允许六方氮化硼 β、菱锰 β、粗制绿宝石 β，魔力还允许红宝石 β、红宝石 γ、天气水晶 β。",
      "badgeText": "力量 → 拔刀剑伤害系数",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "aether:zanite_gemstone",
      "kind": 24,
      "name": "紫晶石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产力量；主手可损坏物品的当前损耗比例越高，额外产分越高；无可损坏物品时保持基础产分。",
      "badgeText": "力量 → 攻击力",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "aether:zanite_gemstone",
      "kind": 24,
      "name": "紫晶石",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取力量，主手可损坏物品的剩余耐久比例越高，额外放大越强；无可损坏物品时无耐久奖励。",
      "badgeText": "力量 → 暴击伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "twilightforest:carminite",
      "kind": 25,
      "name": "砷铅铁矿石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产魔力；实际火焰伤害接近固定目标时奖励提高，达到目标后保持满条件收益。",
      "badgeText": "魔力 → 火焰伤害",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "twilightforest:carminite",
      "kind": 25,
      "name": "砷铅铁矿石",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取魔力；实际火焰伤害、寒冰伤害各自达到固定目标时，分别追加一次乘增。",
      "badgeText": "魔力 → 火焰伤害、寒冰伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "twilightforest:carminite",
      "kind": 25,
      "name": "砷铅铁矿石",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取力量转魔力；实际癫火伤害接近固定目标时，额外转换效率提高，达到后保持。",
      "badgeText": "魔力 → 癫火伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "thermal:apatite",
      "kind": 26,
      "name": "磷灰石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产体质；实际受到治疗倍率接近固定目标时额外产分提高，逐渐趋于满条件收益。",
      "badgeText": "体质 → 受到治疗倍率",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "thermal:apatite",
      "kind": 26,
      "name": "磷灰石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取体质转感知；当前生命比例越高，效率越好，满生命时达到完整条件收益。",
      "badgeText": "感知 → 经验获取",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "thermal:cinnabar",
      "kind": 27,
      "name": "朱砂",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产魔力；每条正面固定值附加修饰追加一次乘增，百分比修饰仍正常影响三维。",
      "badgeText": "魔力 → 癫火伤害",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "thermal:cinnabar",
      "kind": 27,
      "name": "朱砂",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取力量，转换总量分给魔力及智力；正面百分比附加修饰越多，魔力份额越高，剩余为智力。",
      "badgeText": "魔力 → 火焰伤害",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "thermal:niter",
      "kind": 28,
      "name": "硝石",
      "primary": "alpha",
      "letter": "α",
      "role": "amplifier",
      "mechanic": "读取最高力量，输出力量×(1＋力量/K)；还允许读取振动水晶 α。",
      "badgeText": "力量 → 盔甲撕裂",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "thermal:niter",
      "kind": 28,
      "name": "硝石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "从不同邻格读取硝石 α或砷化硼 β的力量及原生魔力，将乘积/K转为魔力。",
      "badgeText": "魔力 → 火焰伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "thermal:ruby",
      "kind": 29,
      "name": "红宝石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产力量；当前生命比例越低，产分越高，30%及以下获得最高条件倍率。",
      "badgeText": "力量 → 攻击力",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "thermal:ruby",
      "kind": 29,
      "name": "红宝石",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "实际攻击力≥1200时读取两个最高原生魔力，低于时读取一个；两份输入先求和，再放大为魔力。",
      "badgeText": "魔力 → 暴击伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "thermal:ruby",
      "kind": 29,
      "name": "红宝石",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取原生体质；较高生命时保留复制体质并生成少量魔力，较低生命时将复制体质转为更多魔力；围绕30%生命平滑过渡。",
      "badgeText": "魔力 → 火焰伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "thermal:sapphire",
      "kind": 30,
      "name": "蓝宝石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产智力；当前潜行时追加乘增。",
      "badgeText": "智力 → 暴击伤害",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "thermal:sapphire",
      "kind": 30,
      "name": "蓝宝石",
      "primary": "beta",
      "letter": "β",
      "role": "amplifier",
      "mechanic": "读取魔力，输出魔力×(1＋魔力/K)^p；加权三维越好，指数p越接近固定极限；还允许红宝石 β、红宝石 γ、天气水晶 β。",
      "badgeText": "魔力 → 寒冰伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "thermal:sapphire",
      "kind": 30,
      "name": "蓝宝石",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取蓝宝石 β、红宝石 β、红宝石 γ或天气水晶 β的魔力，保留(1−g)份额，将g份额转为智力。",
      "badgeText": "智力 → 魔法穿透",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "appflux:charged_redstone",
      "kind": 31,
      "name": "充能红石",
      "primary": "alpha",
      "letter": "α",
      "role": "converter",
      "mechanic": "只读取相邻来源的基础总分B，选择最高者转为智力。",
      "badgeText": "智力 → 魔法穿透",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "appflux:charged_redstone",
      "kind": 31,
      "name": "充能红石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取一颗来源，B部分转敏捷，Δ部分转智力，分别使用固定系数；来源选择策略尚待确定。",
      "badgeText": "敏捷＋智力 → 经验获取",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "tofucraft:tofugem",
      "kind": 32,
      "name": "豆腐宝石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产体质；当前饥饿值越高，额外产分越高，满饥饿值获得完整条件收益。",
      "badgeText": "体质 → 受到治疗倍率",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "tofucraft:tofugem",
      "kind": 32,
      "name": "豆腐宝石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取力量，固定总转换量分为体质、魔力；饥饿值较高时偏体质，较低时偏魔力，比例平滑变化。",
      "badgeText": "体质 → 最大生命值",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "tofucraft:zundaruby",
      "kind": 33,
      "name": "毛豆宝石",
      "primary": "alpha",
      "letter": "α",
      "role": "producer",
      "mechanic": "自产敏捷；每颗相邻宝石的修正后大小越接近自身，提供的额外倍率越高，匹配程度连续变化。",
      "badgeText": "敏捷 → 暴击率",
      "main": "size",
      "badgeMain": "purity"
    },
    {
      "item": "tofucraft:zundaruby",
      "kind": 33,
      "name": "毛豆宝石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取不同邻格的原生体质、感知，汇总转敏捷；两个来源修正后纯度越接近，额外转换倍率越高。",
      "badgeText": "敏捷 → 暴击伤害",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "cataclysm:lacrima",
      "kind": 34,
      "name": "泪宝石",
      "primary": "alpha",
      "letter": "α",
      "role": "amplifier",
      "mechanic": "从三个不同邻格读取其他宝石的加工魔力、智力、感知，输出魔力×(1＋智力/K₁)×(1＋感知/K₂)。",
      "badgeText": "魔力 → 癫火伤害",
      "main": "purity",
      "badgeMain": "polish"
    },
    {
      "item": "cataclysm:lacrima",
      "kind": 34,
      "name": "泪宝石",
      "primary": "beta",
      "letter": "β",
      "role": "converter",
      "mechanic": "读取2–3颗名单内混合分加工宝石，汇总转智力；每多一种实际正分数类型，追加一次固定连乘。",
      "badgeText": "智力 → 拔刀剑伤害系数",
      "main": "polish",
      "badgeMain": "purity"
    },
    {
      "item": "cataclysm:lacrima",
      "kind": 34,
      "name": "泪宝石",
      "primary": "gamma",
      "letter": "γ",
      "role": "converter",
      "mechanic": "读取三颗不同主修饰规则的其他加工宝石，取最终总分最小值X，以X(1＋X/K)²转为体质。",
      "badgeText": "体质 → 最大生命值、受到治疗倍率",
      "main": "polish",
      "badgeMain": "size"
    },
    {
      "item": "cataclysm:lacrima",
      "kind": 34,
      "name": "泪宝石",
      "primary": "delta",
      "letter": "δ",
      "role": "converter",
      "mechanic": "读取一颗其他加工宝石，以其最大分数×(1＋其余分数之和/K)转为力量，选择计算收益最高的来源。",
      "badgeText": "力量 → 攻击力、盔甲撕裂",
      "main": "polish",
      "badgeMain": "size"
    }
  ]
};
