cantWrapperItems = []

[Schematic]
	#一次最多掉落的附魔耀魂数量
	maxEnchantedSoulDrop = 8
	#一个附魔耀魂所需杀敌数的量
	enchantedSoulDropNeeded = 40
	#一次最多掉落的普通耀魂数量
	maxSoulDrop = 20
	#一个普通耀魂所需耀魂值的量
	soulDropNeeded = 150
	#是否添加ciallo的两个原理图（联动）
	enableCiallo = true
	#设定 剑魂映射 中 锻造影响值 的公式
	#  COMMON : refine -> (18 * refine + 100) / (9 * refine + 1000)
	#  NONE : refine -> 1
	#  LOGARITHM : refine -> Math.log((refine + 50) / 50)
	#  BT : refine -> 0.1 + refine / 25
	#Allowed Values: COMMON, NONE, LOGARITHM, BT
	soulBladeMappingRule = "COMMON"

