#最远的渲染距离，超出此半径的不渲染
showDistance = 64
#最多渲染的数字量
maxShowRender = 128
#启用渲染的最小数值
minValueDisplay = 2.1
#是否启用渲染数字合并
enableCombineString = false
#合并生成在多少tick以内的文字
mergeMaxAge = 40.0
#伤害数字存活时间（tick）
#Range: 5 ~ 600
damageStringLife = 30

