#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 08 21:03:16 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableTextureMaterialFallback=true
enableDebugOptions=false
blockUnknownShaders=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
