ServerEvents.highPriorityData(event => {

    tetraMaterialBuilder(event, "fantasy_bubble").setCategory("metal")
        .setPrimary(6).setSecondary(6).setTertiary(3)
        .setDurability(42).setIntegrityCost(1).setIntegrityGain(1)
        .setMagicCapacity(130).setToolLevel(3).setToolEfficiency(8)
        .addAttributes("attributeslib:cold_damage", 3)
        .addAttributes("attributeslib:armor_pierce", 1)
        .addAttributes("slashblade_sendims:magic_penetration", 1)
        .setTints("fbc9ff", "3b48ff") 
        .addTexture("shiny").addTexture("metal")
        .addItemMaterial('sdbf:fantasy_bubble')
        .setRequiredTool("hammer_dig", 1)
        .build();

    tetraMaterialBuilder(event, "chaos_anchor").setCategory("metal")
        .setPrimary(40).setSecondary(20).setTertiary(20)
        .setDurability(42).setIntegrityCost(1).setIntegrityGain(1)
        .setMagicCapacity(127).setToolLevel(3).setToolEfficiency(8)
        .addAttributes("attributeslib:life_steal", 0.0001)
        .addEffects("bleeding", 6)
        .setTints("6e0000", "961c00") 
        .addTexture("shiny").addTexture("metal")
        .addItemMaterial('sdbf:chaos_anchor')
        .setRequiredTool("hammer_dig", 1)
        .build();

    tetraMaterialBuilder(event, "dream_cat").setCategory("metal")
        .setPrimary(3).setSecondary(1).setTertiary(1.5)
        .setDurability(42).setIntegrityCost(1).setIntegrityGain(1)
        .setMagicCapacity(108).setToolLevel(3).setToolEfficiency(9)
        .addAttributes("minecraft:generic.luck", 0.1)
        .addEnchantment("minecraft:fortune", 1.5)
        .setTints("F5B8EB", "FCF6F4") 
        .addTexture("shiny").addTexture("metal")
        .addItemMaterial('sdbf:dream_cat')
        .setRequiredTool("hammer_dig", 1)
        .build();

    tetraMaterialBuilder(event, "stationary_matter").setCategory("fabric")
        .setPrimary(4).setSecondary(2).setTertiary(2.2)
        .setDurability(42).setIntegrityCost(1).setIntegrityGain(1)
        .setMagicCapacity(42).setToolLevel(3).setToolEfficiency(9)
        .addAttributes("**minecraft:generic.max_health", 0.001)
        .addAttributes("**minecraft:generic.movement_speed", 0.001)
        .addAttributes("**minecraft:generic.knockback_resistance", 0.001)
        .addAttributes("**minecraft:generic.attack_damage", 0.001)
        .addAttributes("**minecraft:generic.armor", 0.001)
        .addAttributes("**minecraft:generic.armor_toughness", 0.001)
        .addAttributes("**minecraft:generic.luck", 0.001)
        .addAttributes("**attributeslib:armor_pierce", 0.001)
        .addAttributes("**attributeslib:armor_shred", 0.001)
        .addAttributes("**attributeslib:crit_chance", 0.001)
        .addAttributes("**attributeslib:crit_damage", 0.001)
        .addAttributes("**attributeslib:dodge_chance", 0.001)
        .addAttributes("**attributeslib:experience_gained", 0.001)
        .addAttributes("**attributeslib:fire_damage", 0.001)
        .addAttributes("**attributeslib:cold_damage", 0.001)
        .addAttributes("**attributeslib:life_steal", 0.001)
        .addAttributes("**forge:block_reach", 0.001)
        .addAttributes("**forge:entity_reach", 0.001)
        .addAttributes("**slashblade_sendims:ap_reduce_amount", 0.001)
        .addAttributes("**slashblade_sendims:ap_gain_percentage", 0.001)
        .addAttributes("**slashblade_sendims:sprint_cd", 0.001)
        .addAttributes("**slashblade_sendims:sprint_cd_return", 0.001)
        .addAttributes("**slashblade_sendims:parry_heal_amount", 0.001)
        .addAttributes("**slashblade_sendims:madness_reduce", 0.001)
        .addAttributes("**slashblade_sendims:frenzy_resistance", 0.001)
        .addAttributes("**slashblade_sendims:frenzy_damage", 0.001)
        .addAttributes("**slashblade_sendims:magic_resistance", 0.001)
        .addAttributes("**slashblade_sendims:magic_penetration", 0.001)
        .setTints("87ff5e", "e2ffd9") 
        .addTexture("heavy").addTexture("crude")
        .addItemMaterial('sdbf:stationary_matter')
        .setRequiredTool("hammer_dig", 1)
        .build();

    tetraMaterialBuilder(event, "flammable_ingot").setCategory("metal")
        .setPrimary(14).setSecondary(13).setTertiary(9.5)
        .setDurability(41).setIntegrityCost(1).setIntegrityGain(1)
        .setMagicCapacity(116).setToolLevel(3).setToolEfficiency(9)
        .addAttributes("attributeslib:fire_damage", 4)
        .addEnchantment("minecraft:fire_aspect", 1)
        .addEnchantment("minecraft:fire_protection", 1)
        .setTints("FFE7E3", "E0E0E0") 
        .addTexture("metal")
        .addItemMaterial('sdbf:flammable_ingot')
        .setRequiredTool("hammer_dig", 1)
        .build();
})